### ISSUE TITLE
Config option to limit the CPU and RAM Quotas for Containers

### ISSUE THREAD

**Issue by Mtze** [Mtze/hades#53]
1. We need a config option in our API spec to limit the resources for build containers 
2. We need a global config that limits the ressources to a maximum

**Comment by robertjndw** [comment]
What is meant with `global maximum` @Mtze ?
- Is it a limit that overrides the API limit (e.g. each container gets `min(globalLimit, apiLimit)` as resources)?
- Defines the maximum sum of all container resources? What happens if a container is queued which would exceed this limit?
